server:
  port: 8080
#  ssl:
#    enabled: true
#    key-store: classpath:keystore.p12
#    key-store-password: extract
#    key-store-type: PKCS12
external:
  api:
    base-url: https://article-extractor2.p.rapidapi.com
    key: 2f5f661de0mshf240544b7950535p142c34jsn2606d484365b
    host: article-extractor2.p.rapidapi.com

tts:
  google:
    credentials-path: src/main/resources/google/tts-key.json